# Generated by Django 5.2 on 2025-05-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title', 'price'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
