# Generated by Django 5.2 on 2025-05-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='advertisement',
        ),
    ]
