# Generated by Django 5.2 on 2025-05-03 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_camp', '0004_remove_advertisement_client'),
        ('clients', '0002_remove_client_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='adv_camp.advertisement'),
        ),
    ]
