# Generated by Django 5.2 on 2025-05-02 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_alter_service_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('promotion_channel', models.CharField(db_index=True, max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisement', to='services.service')),
            ],
            options={
                'verbose_name': 'Advertisement campaign',
                'verbose_name_plural': 'Advertising campaigns',
                'ordering': ['title', 'budget'],
            },
        ),
    ]
