# Generated by Django 5.2 on 2025-05-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_camp', '0001_initial'),
        ('services', '0003_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='services.service'),
        ),
    ]
