# Generated by Django 5.2 on 2025-05-03 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_clients', '0001_initial'),
        ('adv_camp', '0002_alter_advertisement_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='client',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='active_clients.activeclient'),
            preserve_default=False,
        ),
    ]
