# Generated by Django 5.2 on 2025-05-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_camp', '0003_advertisement_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='client',
        ),
    ]
