# Generated by Django 5.2 on 2025-05-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(null=True)),
                ('validity_period', models.CharField(max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('file', models.FileField(null=True, upload_to='contracts/documents/')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='services.service')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['title'],
            },
        ),
    ]
