# Generated by Django 5.2 on 2025-05-03 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_clients', '0001_initial'),
        ('contracts', '0004_contract_client_alter_contract_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='active_clients.activeclient'),
            preserve_default=False,
        ),
    ]
