# Generated by Django 5.2 on 2025-05-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contract_end_date_contract_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='validity_period',
        ),
    ]
