# Generated by Django 5.2 on 2025-05-03 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_remove_client_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_client', to='clients.client')),
            ],
            options={
                'verbose_name': 'Active client',
                'verbose_name_plural': 'Active clients',
                'ordering': ['client'],
            },
        ),
    ]
